# Generated by Django 4.0 on 2023-10-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_review_image',
            field=models.FileField(null=True, upload_to='product_images'),
        ),
    ]
