# Generated by Django 4.0 on 2023-10-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_category_is_sub_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_category',
            new_name='super_category',
        ),
    ]
