# Generated by Django 4.0 on 2023-10-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_text_review_review_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
