# Generated by Django 4.0 on 2023-11-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_review_user_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_review_image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
