# Generated by Django 4.0 on 2023-10-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_in_stock'),
        ('shop', '0009_rename_sub_category_category_super_category'),
    ]

    operations = [
    ]
