# Generated by Django 5.0 on 2024-01-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_review_user_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_review_image',
            field=models.ImageField(null=True, upload_to='review_images'),
        ),
    ]
